#!/bin/bash
virtualenv venv
source venv/bin/activate
pip install django
pip install -e ../

mkdir media static
python manage.py syncdb --noinput
python manage.py collectstatic --noinput
echo "Setup Complete."
