#!/bin/bash
virtualenv venv
source venv/bin/activate
pip install django
cd .. && python setup.py install && cd -
mkdir media static
python manage.py syncdb
python manage.py collectstatic
echo "Setup Complete."
